name: Nsight Deployment on EC2 Instances
on:
  push:
    branches:
      - kops

env:
  DOCKER_HUB_USERNAME: stiveckamash #${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: xxxxxxx #${{ secrets.DOCKER_HUB_PASSWORD }}
  EC2_HOST: 54.221.126.9 #${{ secrets.EC2_HOST }}
  EC2_USERNAME: ubuntu #${{ secrets.EC2_USERNAME }}
  EC2_SSH_KEY: xxxxxxxxxxxxxxxxxxxxx #${{ secrets.EC2_SSH_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/Nsightfront:${{ github.sha }} .
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          docker push $DOCKER_HUB_USERNAME/Nsightfront:${{ github.sha }}
      - name: SSH into EC2 instance to access it..
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}

      - name: Deploy Docker image to EC2 instance
        run: |
          docker pull $DOCKER_HUB_USERNAME/Nsightfront:${{ github.sha }}
          docker stop Nsightfront || true
          docker rm Nsightfront || true
          docker run -d -p 3000:3000 --name Nsightfront $DOCKER_HUB_USERNAME/Nsightfront:${{ github.sha }}
