name: Deploy NSIGHT FRONTEND APP

on:
  push:
    branches: 
      - '*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  DOCKER_USERNAME: neuralsight
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code After Push to Git Action
        uses: actions/checkout@v2


      - name: Make Environment File for the Image
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_NEXT_PUBLIC_NEURALSIGHT_API_BASE_URL: https://backend.neuralsight.ai/api/v1
          envkey_ALLOWED_ORGINS: https://www.neuralsight.ai
          some_other_variable: foobar
          file_name: .env
          fail_on_empty: false

      - name: Login to DockerHub for Nsight Account
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}


      - name: Build Docker image for the Nsight App
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/nsightfrontend:latest

      - name: Push Docker image to DockerHub Nsight Account
        run: docker push ${{ env.DOCKER_USERNAME }}/nsightfrontend:latest



      - name: Deploy Docker image to EC2 Automatically
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_HOST  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.SSH_PRIVATE_KEY  }}
          port: 22
          script: |
            echo "I'm At EC2 Server running deployment commands"
            cd NeuralSight_frontend &&
            git pull origin main && 
            sudo docker-compose pull && 
            sudo docker-compose -f docker-compose.yml up -d
            echo "Done Deployning the new Image"
          
