name: Deploy NSIGHT FRONTEND APP

on:
  push:
    branches: 
      - '*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  DOCKER_USERNAME: stiveckamash
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code After Push to Git Action
        uses: actions/checkout@v2

      - name: Login to DockerHub for Nsight Account
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}


      - name: Build Docker image for the Nsight App
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/nsightfrontend:latest

      - name: Push Docker image to DockerHub Nsight Account
        run: docker push ${{ env.DOCKER_USERNAME }}/nsightfrontend:latest



